name: Shellcheck

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Pull shellcheck
      run: docker pull koalaman/shellcheck

    - uses: actions/checkout@v1
    - name: Run shellcheck
      run: "docker run -v $(pwd):/scripts koalaman/shellcheck /scripts/bing-wallpaper.sh"
